imports:
# General
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
# Base
    - { resource: base/a2lix_translation_form.yml }
    - { resource: base/knp_doctrine_behaviors.yml }
    - { resource: base/doctrine.yml }
    - { resource: base/fos_user.yml }
    - { resource: base/swiftmailer.yml }
    - { resource: base/twig.yml }
    - { resource: base/ivory_ckeditor.yml }
# Sonata
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_clasification.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_user.yml }

# Sortable
    - { resource: sortable/pix_sortable_behavior.yml }
    - { resource: sortable/stof_doctrine_extensions.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    locales: [en]
    assets_version: 9.0.0

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    templating:
            engines: ['twig']
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: ~
#         handler_id: session.handler.native_file
#         save_path: /var/lib/php/sessions
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
