# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    acl:
        connection: default

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        backoffice:
            pattern:            /backoffice(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /backoffice/login
                use_forward:    false
                check_path:     /backoffice/login_check
                failure_path:   null
            logout:
                path:           /backoffice/logout
                target:         /backoffice/login
            anonymous:          true

        main:
            pattern:             .*
            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:             true
            anonymous:          true

    access_control:
        - { path: ^/backoffice/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/backoffice/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }