sonata_classification:
    class:
        tag: Application\Sonata\ClassificationBundle\Entity\Tag
        category: Application\Sonata\ClassificationBundle\Entity\Category
        collection: Application\Sonata\ClassificationBundle\Entity\Collection
        context: Application\Sonata\ClassificationBundle\Entity\Context