a2lix_translation_form:
    locale_provider: default
    locales: [en, fr, es, ca]
    default_locale: en
    required_locales: [es,ca]
    templating: "@A2lixTranslationForm/bootstrap_4_layout.html.twig"